export const currencies = [
  { label: "USD (United States Dollar)", value: "USD", icon: "🇺🇸" },
  { label: "EUR (Euro)", value: "EUR", icon: "🇪🇺" },
  { label: "JPY (Japanese Yen)", value: "JPY", icon: "🇯🇵" },
  { label: "GBP (British Pound Sterling)", value: "GBP", icon: "🇬🇧" },
  { label: "AUD (Australian Dollar)", value: "AUD", icon: "🇦🇺" },
  { label: "CAD (Canadian Dollar)", value: "CAD", icon: "🇨🇦" },
  { label: "CHF (Swiss Franc)", value: "CHF", icon: "🇨🇭" },
  { label: "CNY (Chinese Yuan)", value: "CNY", icon: "🇨🇳" },
  { label: "SEK (Swedish Krona)", value: "SEK", icon: "🇸🇪" },
  { label: "NZD (New Zealand Dollar)", value: "NZD", icon: "🇳🇿" },
  { label: "MXN (Mexican Peso)", value: "MXN", icon: "🇲🇽" },
  { label: "SGD (Singapore Dollar)", value: "SGD", icon: "🇸🇬" },
  { label: "HKD (Hong Kong Dollar)", value: "HKD", icon: "🇭🇰" },
  { label: "NOK (Norwegian Krone)", value: "NOK", icon: "🇳🇴" },
  { label: "KRW (South Korean Won)", value: "KRW", icon: "🇰🇷" },
  { label: "TRY (Turkish Lira)", value: "TRY", icon: "🇹🇷" },
  { label: "RUB (Russian Ruble)", value: "RUB", icon: "🇷🇺" },
  { label: "INR (Indian Rupee)", value: "INR", icon: "🇮🇳" },
  { label: "BRL (Brazilian Real)", value: "BRL", icon: "🇧🇷" },
  { label: "ZAR (South African Rand)", value: "ZAR", icon: "🇿🇦" },
  { label: "DKK (Danish Krone)", value: "DKK", icon: "🇩🇰" },
  { label: "PLN (Polish Zloty)", value: "PLN", icon: "🇵🇱" },
  { label: "TWD (New Taiwan Dollar)", value: "TWD", icon: "🇹🇼" },
  { label: "THB (Thai Baht)", value: "THB", icon: "🇹🇭" },
  { label: "MYR (Malaysian Ringgit)", value: "MYR", icon: "🇲🇾" },
  { label: "IDR (Indonesian Rupiah)", value: "IDR", icon: "🇮🇩" },
  { label: "CZK (Czech Koruna)", value: "CZK", icon: "🇨🇿" },
  { label: "HUF (Hungarian Forint)", value: "HUF", icon: "🇭🇺" },
  { label: "ILS (Israeli New Shekel)", value: "ILS", icon: "🇮🇱" },
  { label: "PHP (Philippine Peso)", value: "PHP", icon: "🇵🇭" },
  { label: "AED (United Arab Emirates Dirham)", value: "AED", icon: "🇦🇪" },
];
